import type { ProductoInterno } from '@/features/productos/types/producto.types'

export const CATEGORIAS_MOCK = [
  { id: '1', nombre: 'Electrónica', slug: 'electronica' },
  { id: '2', nombre: 'Computación', slug: 'computacion' },
  { id: '3', nombre: 'Celulares', slug: 'celulares' },
  { id: '4', nombre: 'Hogar', slug: 'hogar' },
  { id: '5', nombre: 'Deportes', slug: 'deportes' },
  { id: '6', nombre: 'Herramientas', slug: 'herramientas' },
]

export const PRODUCTOS_MOCK: ProductoInterno[] = [
  {
    id: '1',
    nombre: 'Auriculares Bluetooth JBL Tune 510BT',
    descripcion: 'Auriculares inalámbricos con hasta 40 horas de batería, sonido Pure Bass y plegables para mayor comodidad.',
    precio: 28500,
    precioOriginal: 35000,
    imagenes: ['https://placehold.co/400x400/e8640b/white?text=JBL+510BT'],
    categoriaId: '1',
    stock: 15,
    slug: 'auriculares-jbl-tune-510bt',
    activo: true,
  },
  {
    id: '2',
    nombre: 'Mouse Inalámbrico Logitech M185',
    descripcion: 'Mouse inalámbrico compacto con receptor USB nano, 12 meses de batería y diseño ambidiestro.',
    precio: 8900,
    precioOriginal: 11500,
    imagenes: ['https://placehold.co/400x400/2968C8/white?text=Logitech+M185'],
    categoriaId: '2',
    stock: 42,
    slug: 'mouse-logitech-m185',
    activo: true,
  },
  {
    id: '3',
    nombre: 'Teclado Mecánico Redragon K552',
    descripcion: 'Teclado mecánico compacto TKL con switches rojos, retroiluminación RGB y construcción metálica.',
    precio: 22000,
    imagenes: ['https://placehold.co/400x400/333333/white?text=Redragon+K552'],
    categoriaId: '2',
    stock: 8,
    slug: 'teclado-redragon-k552',
    activo: true,
  },
  {
    id: '4',
    nombre: 'Cargador Inalámbrico 15W Qi',
    descripcion: 'Cargador inalámbrico rápido compatible con iPhone y Android, base antideslizante.',
    precio: 6500,
    precioOriginal: 9000,
    imagenes: ['https://placehold.co/400x400/00A650/white?text=Cargador+Qi'],
    categoriaId: '3',
    stock: 30,
    slug: 'cargador-inalambrico-15w',
    activo: true,
  },
  {
    id: '5',
    nombre: 'Smartwatch Xiaomi Band 8',
    descripcion: 'Pulsera inteligente con monitor de frecuencia cardíaca, SpO2, 16 días de batería y resistencia al agua.',
    precio: 34900,
    precioOriginal: 42000,
    imagenes: ['https://placehold.co/400x400/e8640b/white?text=Mi+Band+8'],
    categoriaId: '3',
    stock: 20,
    slug: 'xiaomi-band-8',
    activo: true,
  },
  {
    id: '6',
    nombre: 'Parlante Bluetooth Anker Soundcore 2',
    descripcion: 'Parlante portátil con 24 horas de reproducción, resistencia al agua IPX7 y graves potentes.',
    precio: 19800,
    imagenes: ['https://placehold.co/400x400/2968C8/white?text=Soundcore+2'],
    categoriaId: '1',
    stock: 12,
    slug: 'parlante-anker-soundcore-2',
    activo: true,
  },
  {
    id: '7',
    nombre: 'Webcam Full HD Logitech C920',
    descripcion: 'Webcam 1080p con enfoque automático, corrección de luz y micrófono estéreo incorporado.',
    precio: 45000,
    precioOriginal: 58000,
    imagenes: ['https://placehold.co/400x400/333333/white?text=C920'],
    categoriaId: '2',
    stock: 5,
    slug: 'webcam-logitech-c920',
    activo: true,
  },
  {
    id: '8',
    nombre: 'Cable USB-C a USB-C 1m Anker',
    descripcion: 'Cable de carga rápida 60W con trenzado de nylon, compatible con todos los dispositivos USB-C.',
    precio: 3200,
    imagenes: ['https://placehold.co/400x400/00A650/white?text=Cable+USB-C'],
    categoriaId: '1',
    stock: 100,
    slug: 'cable-usb-c-anker',
    activo: true,
  },
]
